# Generated by Django 5.1.2 on 2024-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
